"""Search client — LLM-powered mock (works without an external search API key)."""

import json
import logging

from multi_agent_research_lab.core.schemas import SourceDocument

logger = logging.getLogger(__name__)

_SYSTEM = """You are a search engine simulator.
Given a research query, generate realistic and informative search results.
Return ONLY a raw JSON array (no markdown fences, no explanation) like:
[
  {"title": "...", "url": "https://...", "snippet": "2-3 sentence factual summary..."},
  ...
]
Make results diverse: mix academic papers, technical blog posts, and official documentation.
Each snippet should be substantive and directly relevant to the query."""


class SearchClient:
    """LLM-powered mock search — returns plausible sources without an external API."""

    def __init__(self) -> None:
        from multi_agent_research_lab.services.llm_client import LLMClient

        self._llm = LLMClient(temperature=0.5)

    def search(self, query: str, max_results: int = 5) -> list[SourceDocument]:
        """Return mock search results generated by the LLM."""
        user = (
            f'Research query: "{query}"\n'
            f"Generate exactly {max_results} diverse search results as a JSON array."
        )
        try:
            resp = self._llm.complete(_SYSTEM, user)
            # Strip potential markdown fences just in case
            raw = resp.content.strip()
            if raw.startswith("```"):
                raw = raw.split("```")[1]
                if raw.startswith("json"):
                    raw = raw[4:]
            data: list[dict] = json.loads(raw)
            docs = [SourceDocument(**item) for item in data[:max_results]]
            logger.debug("Search returned %d results for: %s", len(docs), query[:60])
            return docs
        except Exception as exc:
            logger.warning("Search LLM call failed (%s), using fallback.", exc)
            return [
                SourceDocument(
                    title=f"Overview of {query}",
                    url=f"https://example.com/search?q={query[:40].replace(' ', '+')}",
                    snippet=(
                        f"A comprehensive overview of {query}, covering key concepts, "
                        "current approaches, and recent developments in the field."
                    ),
                )
            ]
